### ISSUE TITLE
Integrate with WalletConnect

### ISSUE THREAD

**Issue by alejomendoza** [stellar/freighter#489] opened 2022-05-13 16:57 UTC
### What problem does your feature solve?

Interoperability across the Stellar ecosystem and leverage of tools like Lobstr Vault signer.

### What would you like to see?

A way you can connect to Freighter via [WalletConnect](https://docs.walletconnect.com/2.0/). 

### What alternatives are there?

Almost none existent.

**Comment by piyalbasu** [comment] 2024-01-26 00:06
Duplicate of #289

**Closed by piyalbasu** 2024-01-26 00:06 UTC
Labels: triage
